### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by slaecker** [themadmrj/ircapp#1]
I followed the MIN Version install method to install ircapp on my Raspberry Pi running Raspbian Jessie. After installing the dependencies and deb file I get:

```
$ ircapp 
Traceback (most recent call last):
  File "/usr/bin/ircapp", line 9, in <module>
    load_entry_point('ircapp==1.1.1', 'gui_scripts', 'ircapp')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python3/dist-packages/ircapp/main.py", line 14, in <module>
    from ircapp.ircapp.models import *
  File "/usr/lib/python3/dist-packages/ircapp/ircapp/models.py", line 4, in <module>
    class Download_History(models.Model):
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

I did a quick google search and what I've found makes me think something in the code needs fixing. Otherwise please let me know what I am missing.

**Comment by jonasN5** [comment]
Hi slaecker,

someone came with a similar issue not so long ago. He wanted to implement ircapp on a NAS to have the server perma run it and manage the application with another device, an ipad for instance. It works now.
However, your Raspbetty Pi is ARM based. Therefore, any .deb package, which is automatically x64 or x86 architecture specific, will not work.
I might also add that a Raspberry Pi as NAS solution isn't the best idea. You would have to plug your hdd as usb and the cpu is quite slow to decompress files. Furthermore, if you add additionnal costs, a ready-to-go NAS such as the zyxel nsa325v2 is less expensive and much faster.
If you still want to try with your setup, you need to use the unpackaged script : don't use a .deb, fork the source code from github and create your own shortcut to the main.py script to run ircapp.

J.

**Comment by slaecker** [comment]
Thanks for your reply @themadmrj 

I initially thought python was architecture independent and as soon as you have it installed on your computer or whatever you can run any python application. Now I learned something new which is actually a good thing :smiley: 

I plan to use ircapp just for downloading on the Raspberry Pi which is running 24/7. I have another "homeserver" which only runs on demand (to save energy/the planet ... you know). The latter will grab all downloaded files automatically and unpack them etc as soon as itʹs running so no need for (another) NAS here but thanks for the suggestion.

So with fork you mean clone right? Or will I have to make any changes to the source code to make it run on ARM?

**Comment by jonasN5** [comment]
Nope. Juste clone/copy the source code and it should work, just as it did
for the other guy :)

**Comment by slaecker** [comment]
Thanks for the confirmation, however i run into an issue when executing `main.py`

```
$ python /opt/ircapp/main.py 
Traceback (most recent call last):
  File "/opt/ircapp/main.py", line 5, in <module>
    import requests
ImportError: No module named requests
```

I reviewed the install log of the pip3 command and saw:

```
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages
Cleaning up...
```

Then I ran

```
$ sudo pip3 install requests --upgrade
Downloading/unpacking requests from https://pypi.python.org/packages/99/b4/63d99ba8e189c47d906b43bae18af4396e336f2b1bfec86af31efe2d2cb8/requests-2.10.0-py2.py3-none-any.whl#md5=abf5a77de3e8a5973c738cca884502a0
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB): 506kB downloaded
Installing collected packages: requests
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python3/dist-packages, owned by OS
Successfully installed requests
Cleaning up...
```

But I still get the same error when running `python /opt/ircapp/main.py`

**Comment by jonasN5** [comment]
Try reinstalling after cleaning up.
sudo apt-get purge requests then sudo pip3 install requests.
This sometimes happens with python packages, nothing to do with ircapp.
Take a look at : http://stackoverflow.com/questions/17309288/importerror-no-module-named-requests
