### ISSUE TITLE
linux ubuntu issue 

### ISSUE THREAD

**Issue by m7mdcc** [themadmrj/ircapp#10]
Hello dear,

Thanks for your work .. i have problem with linux install .  in download box dialog , its say : 
Couldn’t find the corresponding download folder, please set one to pursue downloading
Download directory: No directory set 
i cant see change by double click on "No directory set" to change the directory .. can i change its via config.ini ? also when i try to search its say : Download_Path matching query does not exist.

i think its related right ? 

on windows install , there is no problem .. 

Another  Q , does ircapp have api ? to manage download ? 

Thanks

**Comment by jonasN5** [comment]
Hi,

did you use github source code or sourceforge packaged version ?

Regarding the API : no, there is none atm. I couldn't think of a useful case where the locally designed app would require an API. Perhaps an add for a future version !

**Comment by m7mdcc** [comment]
for Download_Path issue i just create folder name "Downloads" on my user directory  "is that default directory ?"  , then its solved .. but still i cant choose another directory to save downloads in it ..   this issue happened on source code and sourceforge packaged version ..

**Comment by jonasN5** [comment]
On windows the choose directory dialog appears properly, but nothing appears on Unix ?

**Comment by m7mdcc** [comment]
Yes, exactly.

**Comment by jonasN5** [comment]
Under Linux, did you run sudo apt-get install python3-tk ?

**Comment by m7mdcc** [comment]
Yes , as doc mentioned .

**Comment by jonasN5** [comment]
At the moment, I am unable to reproduce the problem. The file dialog properly displays for me, both under Windows and Linux. I have implemented a config.ini work around to give you the possibility to change the download directory at will.
