### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by stefanmb** [themadmrj/ircapp#9]
@themadmrj I think it would be good to add an explicit license to the codebase. May I suggest the [MIT License](https://en.wikipedia.org/wiki/MIT_License)? That is, of course, assuming you're okay with a permissive license.

Edit: More info is available here https://help.github.com/articles/open-source-licensing/

**Comment by jonasN5** [comment]
There already is a license :)

**Comment by stefanmb** [comment]
Oh, I missed that - I see it's MIT already. It's possible to select the license in the Github project settings to make it easier to find as per https://help.github.com/articles/open-source-licensing/.

Thanks! :)
